---
Name: headlessconfig
---
Chtombleson\SSHeadless\Extension\StaticJSON:
  default_json_fields:
    - column: ID
      key: id
    - column: GUID
      key: guid
    - column: ClassName
      key: class_name
    - column: Created
      key: created_at
    - column: LastEdited
      key: updated_at

Chtombleson\SSHeadless\Output\Factory:
  writer: Chtombleson\SSHeadless\Output\Writer\Filesystem

Chtombleson\SSHeadless\Output\Writer\Filesystem:
  output_dir: assets/data

Chtombleson\SSHeadless\Output\Writer\S3:
  region: null
  key: null
  secret: null
  bucket: null

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Chtombleson\SSHeadless\Extension\StaticJSON
  json_fields:
    - column: Title
      key: title
    - column: Content
      key: content
    - column: MenuTitle
      key: menu_title
    - column: URLSegment
      key: url_segment
    - column: MetaDescription
      key: meta_description
    - column: ExtraMeta
      key: extra_meta
    - column: ShowInMenus
      key: show_in_menus
    - column: ShowInSearch
      key: show_in_search
    - column: Sort
      key: sort

PageController:
  extensions:
    - Chtombleson\SSHeadless\Extension\PageController
